# Generated by Django 3.1.2 on 2021-01-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicion', '0002_auto_20210107_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicion',
            name='de',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='pagina',
        ),
    ]
