# Generated by Django 3.1.2 on 2021-01-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicion', '0003_auto_20210107_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion_Bienes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisicion_id', models.IntegerField()),
                ('bienes_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='bien_servicio',
        ),
    ]
