from django import forms

from apps.usuario.models import Bienes

class BienesForm(forms.ModelForm):

    class Meta:
        model = Bienes

        fields = [
            'eje_pide',
            'estrategia_pide',
            'programa_poa',
            'componente_poa',
            'proyecto_poa',
            'actividad_poa',
            'entregable_poa',
            'nombre_responsable',
            'area_solicitante',
            'descrip_partida',
            'codigo_partida',
            'codigo_pestatal',
            'descrip_general_bien',
            'espeficaciones_tecnicas',
            'capitulo',
            'tipo',
            'unidad_medida',
            'cantidad_bienes',
            'precio_unitario',
            'total',
            'ingresos_propios',
            'recurso_fiscal',
            'recurso_federal',
            'presupues_total_anual',
            'licitacion_publica',
            'invitacion_personas',
            'adjudicacion_directa',
            'partidas_paaays',
            'cal_enero',
            'cal_febrero',
            'cal_marzo',
            'cal_abril',
            'cal_mayo',
            'cal_junio',
            'cal_julio',
            'cal_agosto',
            'cal_septiembre',
            'cal_octubre',
            'cal_noviembre',
            'cal_diciembre',
            'status',
        ]
        labels = {
            'eje_pide': 'Eje',
            'estrategia_pide': 'Estrategia',
            'programa_poa': 'Proceso/Programa',
            'componente_poa': 'Componente',
            'proyecto_poa': 'Proyecto',
            'actividad_poa': 'Actividad',
            'entregable_poa': 'Entregable',
            'nombre_responsable': 'Nombre Solicitante' ,
            'area_solicitante': 'Área Solicitante',
            'descrip_partida': 'Descripción de la partida',
            'codigo_partida': 'Partida',
            'codigo_pestatal': 'Partida Estatal',
            'descrip_general_bien': 'Descripción general',
            'espeficaciones_tecnicas': 'Especificaciones técnicas',
            'capitulo': 'Capítulo',
            'tipo': 'Tipo',
            'unidad_medida': 'Unidad de Medida',
            'cantidad_bienes': 'Cantidad de bienes o servicios',
            'precio_unitario': 'Precio unitario',
            'total': 'Total',
            'ingresos_propios': 'Ingresos Propios',
            'recurso_fiscal': 'Recurso Fiscal',
            'recurso_federal': 'Recurso Federal',
            'presupues_total_anual': 'Presupuesto Total Anual',
            'licitacion_publica': 'Licitación Publica',
            'invitacion_personas': 'Invitación a cuando menos tres personas',
            'adjudicacion_directa': 'Adjudicación Directa',
            'partidas_paaays': 'Partidas No Sujetas al PAAAyS',
            'cal_enero': 'Enero',
            'cal_febrero': 'Febrero',
            'cal_marzo': 'Marzo',
            'cal_abril': 'Abril',
            'cal_mayo': 'Mayo',
            'cal_junio': 'Junio',
            'cal_julio': 'Julio',
            'cal_agosto': 'Agosto',
            'cal_septiembre': 'Septiembre',
            'cal_octubre': 'Octubre',
            'cal_noviembre': 'Noviembre',
            'cal_diciembre': 'Diciembre',
            'status': 'Status',
        }
        widgets = {
            'eje_pide': forms.Select(attrs={'class': 'form-control'}),
            'estrategia_pide': forms.Select(attrs={'class': 'form-control'}),
            'programa_poa': forms.Select(attrs={'class': 'form-control'}),
            'componente_poa': forms.Select(attrs={'class': 'form-control'}),
            'proyecto_poa': forms.Select(attrs={'class': 'form-control'}),
            'actividad_poa': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Escribe una actividad'}),
            'entregable_poa': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Escribe un entregable'}),
            'nombre_responsable': forms.TextInput(attrs={'class': 'form-control'}), #Es select para traer los solicitantes de la BD
            'area_solicitante': forms.Select(attrs={'class': 'form-control'}),
            'descrip_partida': forms.Select(attrs={'class': 'form-control'}),
            'codigo_partida': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Introduce el código de la partida seleccionada'}),
            'codigo_pestatal': forms.NumberInput(attrs={'class': 'form-control','placeholder': 'Introduce el código de la partida estatal'}),
            'descrip_general_bien': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Escribe una descripción'}),
            'espeficaciones_tecnicas': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Escribe las especificaciones técnicas'}),
            'capitulo': forms.Select(attrs={'class': 'form-control'}),
            'tipo': forms.Select(attrs={'class': 'form-control'}), #Puede ser tipo RadioSelect 
            'unidad_medida': forms.Select(attrs={'class': 'form-control'}),
            'cantidad_bienes': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Introduce la cantidad de bienes o servicios'}),
            'precio_unitario': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Introduce el precio unitario del bien o servicio'}),
            'total': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Introduce el total de acuerdo a la cantidad de bienes o servicios'}),
            'ingresos_propios': forms.NumberInput(attrs={'class': 'form-control'}),
            'recurso_fiscal': forms.NumberInput(attrs={'class': 'form-control'}),
            'recurso_federal': forms.NumberInput(attrs={'class': 'form-control'}),
            'presupues_total_anual': forms.NumberInput(attrs={'class': 'form-control'}),
            'licitacion_publica': forms.NumberInput(attrs={'class': 'form-control'}),
            'invitacion_personas': forms.NumberInput(attrs={'class': 'form-control'}),
            'adjudicacion_directa': forms.NumberInput(attrs={'class': 'form-control'}),
            'partidas_paaays': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_enero': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_febrero': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_marzo': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_abril': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_mayo': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_junio': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_julio': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_agosto': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_septiembre': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_octubre': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_noviembre': forms.NumberInput(attrs={'class': 'form-control'}),
            'cal_diciembre': forms.NumberInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(BienesForm, self).__init__(*args, **kwargs)
        self.fields['descrip_partida'].empty_label ='Selecccionar...'
